### ISSUE TITLE
gene auto-complete in mutations is kind of wacky

### ISSUE THREAD

**Issue by leipzig** [cognoma/frontend#109]
type in `GRIN` - suggests CAMK4 ACSBG1 GSR NR3C1 DCAF6
type in `GRIN2` - suggests GPRIN2
type in `GRIN2A` - suggests GRIN2A GRIN2D GRIN2B

**Comment by ramenhog** [comment]
@dhimmel our search input placeholder text for mutations says "search by name". Do we want that or would researchers rather search by symbol?

**Comment by dhimmel** [comment]
Currently, I see "Search genes by name". I think you could shorten to "Search genes", since our search will look up both symbols and names.

**Comment by ramenhog** [comment]
@dhimmel These are the results I'm getting with the simple query service mygene.info provides for "camk":
<img width="849" alt="screen shot 2018-02-12 at 4 45 03 pm" src="https://user-images.githubusercontent.com/4724065/36121592-b01f3268-1014-11e8-9752-7cd06ef37e9a.png">

Is that alright? It seems to return genes like DCLK2 that don't contain that sequence of letters since it technically searches for everything. I'm not sure there's a way around that unless we do a fielded search, but that also returns interesting results...

**Comment by dhimmel** [comment]
That's because [DCLK2](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:19002) previously used the symbol DCAMKL2. So this is actually working as intended.

If we have problems, we could look into tweaking the mygene.info query. I know there are some things that can be tuned, but not a priority at this time.

**Comment by ramenhog** [comment]
Cool beans. This make it a smaller PR then 🙌
