### ISSUE TITLE
Update success email

### ISSUE THREAD

**Issue by ramenhog** [cognoma/frontend#132]
Currently, they're just plaintext.

![screen shot 2018-02-16 at 9 59 43 am](https://user-images.githubusercontent.com/4724065/36313663-2e066db6-1300-11e8-83e7-1f74ef0e427d.png)

**Comment by ramenhog** [comment]
@dhimmel Did we also want to update the text in any way?

**Comment by dhimmel** [comment]
> Did we also want to update the text in any way?

Yeah. Something like:

***

Your Cognoma classifier is complete. The results are available as a Jupyter notebook. Please see [classifier_120.ipynb]().

This classifier predicts mutations in the following genes: XXX, XXX, XXX. Cancers of the following types were included: XX, XX, XX. In total, XX of XX cancers were mutated for at least one of the query genes.

***

I got rid of the download link because that should be easily available from nbviewer
