### ISSUE TITLE
Angular Service creation: Cognoma Core-Service API intergation 

### ISSUE THREAD

**Issue by bdolly** [cognoma/frontend#28]
Create a service that communicates with the [Cognoma Core-Services API](https://github.com/cognoma/core-service). 

@cgreene @awm33 I see [endpoints documented](https://github.com/cognoma/core-service/blob/master/doc/api.md) but I'm not sure **what the base API url is** or if there is one or if the core-services can be spun up locally to interact with during development. Some guidance here would be appreciated as the back-end stack is outside my area of expertise.

**Comment by awm33** [comment]
@bdolly There is no base URL yet. We were thinking `https://cognoma.org/api` but it could also be a subdomain like `https://api.cognoma.org`

There is some guidance on how to run the API server locally in [the README](https://github.com/cognoma/core-service). I'm working on docker setup which should make that much easier. Docker compose should set up nginx, core-service, task-service, and postgres. Potentially elasticsearch as well.

Development should be done locally and not against production, so being able to change the API base url through the environment or as part of a gulp task would be nice.

This angular service should also be mocked, so unit and integration tests can run without the entire application running.

**Comment by dhimmel** [comment]
@awm33 do you prefer `https://cognoma.org/api` or `https://api.cognoma.org`? Does one option provide us more flexibility or hosting modularity?

Is it the case that our frontend code is all static? For example, we could host it using GitHub Pages? In that case, I think we'd want to use `https://api.cognoma.org` since the API cannot be hosted on GitHub Pages.

**Comment by awm33** [comment]
@dhimmel I think I would prefer `https://api.cognoma.org`. I don't think we can use Github Pages since we can't set Cross Origin Resource Sharing headers.

We could host the static frontend using nginx or even just S3, which supports setting [CORS headers](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) and is almost maintance free.

For local development, some sort of web server would be needed, but it looks like the repo already has a gulp task for that.

**Comment by dhimmel** [comment]
Okay then let us go with `https://api.cognoma.org`.

**Comment by bdolly** [comment]
closed with #51
