### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by awm33** [cognoma/frontend#32]
The backend repos have been set up to use CIrcleCI for Continuous Integration. I think we should set that up on the frontend. Right not this is just for testing CI, so on a change to master, that would run tests in a container on CircleCI. CircleCI is enabled for this Github org, so anyone who is a maintainer can add it to the repo.

We'll also need to pick some test runners, usually a runner like karma and a headless browser like phantom is used.

**Comment by bdolly** [comment]
@awm33 I'm down with this idea. This repo has a `production` branch where all the final changes that need tested would reside, we could run CI tests on that before pushing to `master` so that production would function as a sort of staging area. 

I would need some guidance as to how to set up the testing and it's workings as it's an area I don't have experience in and hoped to learn about with project Cognoma.

**Comment by awm33** [comment]
@bdolly @dhimmel Can you or anyone with permissions add this repo to CircleCI? I can create a circle.yml file to execute the tests if we need to, but I don't have permissions to add CircleCI.

**Comment by dhimmel** [comment]
> Can you or anyone with permissions add this repo to CircleCI?

I believe I added `cognoma/frontend` to CircleCI. See https://circleci.com/gh/cognoma/frontend.

**Comment by awm33** [comment]
@dhimmel Yep, it's working! Looks like we just need to setup a circle.yml

**Comment by bdolly** [comment]
circle ci working on pull request creation
