### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by awm33** [cognoma/frontend#7]
I think it's easier to discuss frontend design using real drawings / wireframes.

Here's my first crack at it. I am not a designer haha.

The styles are based on bootstrap.

![cognoma desktop hd](https://cloud.githubusercontent.com/assets/3846080/17459068/d9afe19e-5bf8-11e6-9a12-277fed58c207.png)

The tabbed Genes input section is incomplete. But that would contain text, file upload, and "Assisted" neo4j powered gene input. The text input could possibly be a type ahead input like tissues. The algorithm and submission summary pages also need to be done. I feel like I don't know enough about what the algorithm page needs to obtain or would look like.

I can iterate based on feedback, or if someone else would like to contribute I can share the source file. It's in [Sketch app](https://www.sketchapp.com/) format.

**Comment by awm33** [comment]
@gwaygenomics and @BobMiller may be interested

**Comment by gwaygenomics** [comment]
@awm33 - This is a great start. The simplistic design is exactly what I had in mind. There are some differences that I think should be clarified (e.g. Users should start with `genes`) I'd love to take a crack at the Sketch app source code- can you pass it along to me? Thanks!

**Comment by awm33** [comment]
@gwaygenomics Would it make more sense for tissue input to be its own optional step? So:
1) Input Genes
2) Select Tissues (Optional)
3) Choose Algorithm
4) Submit

For tissues, I think you said given a list of genes, only certain tissues would be applicable. How would we determine this? A lookup table with an entry for each gene/tissue combo? Would the user still be able to select tissues that we deem not applicable?

Do we know what the user will need to input for the algorithm selection? From what I can gather, it will be a list of algorithms and optionally provide values for parameters. Are we assisting the user is choosing the algorithm? Do we know how we would do that? Would a user be able to select multiple algorithms?

Yeah, Sketch is also paid, still cheaper than Creative Suite. A designer at my company uses it and I find it easier to use then Illustrator, it's also more geared toward UI development.

**Comment by gwaygenomics** [comment]
There are several gene expression based signatures in cancer that are caused by mutations in different genes and pathways (groups of genes involved in a single process). Many of these signals (like `TP53` mutational signature) are consistent in many different types of cancer. Other signatures are unique to certain cancers, but there are also several that overlap only a select number of tissues - this is still very much an active research question, but it has been shown to be true for a [smaller subset of tissues](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4152462/)

> I think you said given a list of genes, only certain tissues would be applicable. How would we determine this?

Only if the tissue has enough mutations across the set of input genes can it be included in the classifier. How do we set the threshold? ...I have used 10 mutations in the past, but we can explore this question further analytically.

> Would the user still be able to select tissues that we deem not applicable?

Short answer: _Maybe_, but for now, probably not. A bit longer answer: This is one of the super tricky aspects of the data we're working with. I've observed that building a classifier to detect mutations in a given gene in a set of tumors does a surprisingly good job of classifying a different gene in a different tissue. Biology is weird! It actually does a much better job than a classifier built using the single tissue with the other gene. Therefore, I think the `tissue selector` should be thought more of like the set of tissues the user cares about classifying correctly. But, if the tissue they care about is _not_ in the set let's consider throwing an exception for now...but this could also be explored further analytically.

> Do we know what the user will need to input for the algorithm selection?

I think anything we decide here would be based on assumptions about what the user will want. Right now, the thought is some sort of [flowchart](http://scikit-learn.org/stable/tutorial/machine_learning_map/ "sklearn flowchart") where a user can select what type of _output_ they want. E.g. Do they want probabilities associated with the classifier? Do they want a sparse solution with interpretable gene lists? etc. The machine learning group has been talking about this a bit in cognoma/machine-learning#5
